ControlFocus( "Open","","Edit1" )
Sleep(3000)
ControlSetText("Open", "","Edit1", "C:\Users\shashank.k.tiwari\Desktop\Tech Talk Demo\ShashankTiwariAutomationArchitect\Assignment Deutsche Bank\TestFiles\ProfilePic.PNG")
Sleep(3000)
ControlClick( "Open", "", "Button1")
Sleep(3000)